### ISSUE TITLE
[BUG] Urgent - regression: in Translate tab, selecting "Chinese" or "German" will crash app

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#100]
- [x] I have looked at [the documentation for the app](https://www.glossarist.org/docs/), and I still believe there is an issue.

**Describe the issue**

1. In Translate tab, select a term
2. Select "Chinese" or "German".
3. See app go into a blank screen. Quit the app, and the macOS "crashed" popup shows.

**When does it happen?**
Steps to reproduce the problem, for example:
1. In Translate tab, select a term
2. Select "Chinese" or "German".
3. See app go into a blank screen. Quit the app, and the macOS "crashed" popup shows.

**Expected behavior**
Should not crash.

**Screenshots**
<img width="1312" alt="Screen Shot 2020-08-19 at 9 44 50 PM" src="https://user-images.githubusercontent.com/11865/90643017-a9689880-e265-11ea-9e25-d19ad2422ed2.png">

**Environment**
macOS Catalina

**Additional context**

**Comment by ronaldtse** [comment]
May be related to ISO 639 B/T codes (Chinese: zho/chi, German ger/deu)

**Comment by strogonoff** [comment]
This is caused by missing revision structure in the data for some (one or more) entries in those languages. I’ll get to the bottom of this but in meantime fix is implemented and release being made.

**Comment by strogonoff** [comment]
The fact that those languages are with B/T code differences may be related (but codes _in the app_ are correct: https://github.com/glossarist/glossarist-desktop/blob/master/src/app.ts#L12). However, missing revision structure needs to be handled properly without crashing anyway.

**Comment by strogonoff** [comment]
The fix was pushed and new version published yesterday, but CI apparently has trouble publishing the next release.

**Comment by ronaldtse** [comment]
Thanks @strogonoff !

**Comment by ronaldtse** [comment]
Still buggy -- app doesn't crash, but cannot show Chinese in Card view when it is clearly in there...

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/11865/90723086-a9f94180-e2ee-11ea-9d39-71d072930ea0.png">

**Comment by strogonoff** [comment]
Yes, this was not fully resolved, only crash fixed.

Apparently, revision structures are missing for some languages. They were [not added](https://github.com/geolexica/isotc211-glossary/commit/ca344a780316f358624091346067518013033e85#diff-f0072aaaffd79768a25f56e7b1c026cfR190) during bulk migration.

This could be due to wrong language codes back _at the time of migration_ made it so that certain language entries were not revision-initialized.

I am looking into resolving that.

**Comment by strogonoff** [comment]
For ISO/TC 211 should be fixed in https://github.com/geolexica/isotc211-glossary/commit/9436dde5ab3e3a7598ba26a3b89807e79ce402b9 now (cc @ronaldtse). I don’t think it’s a problem in OSGeo since they don’t seem to have other languages.
